#!/bin/bash

# kano-safe-mode-triggers.postinst
#
# Copyright (C) 2018 Kano Computing Ltd.
# License: http://www.gnu.org/licenses/gpl-2.0.txt GNU GPLv2
#
# Post debian package install script.


case "$1" in
    configure)
        # Enable system systemd services.
        systemctl enable check-kano-safe-mode.service

        # Enable user systemd services for all users.
        systemctl --global enable check-kano-safe-mode-user.service
        ;;
esac
